jobs:
  paperclip:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Git Repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2.5.0
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Configure Git User Details
      run: git config --global user.email "actions@github.com" && git config --global
        user.name "Github Actions"
    - continue-on-error: true
      name: Apply Patches
      run: ./gradlew applyPatches --stacktrace
    - continue-on-error: true
      name: Build Paperclip jar
      run: ./gradlew shadowjar createReobfPaperclipJar --stacktrace
    - continue-on-error: true
      name: Upload Paperclip jar
      uses: actions/upload-artifact@v2
      with:
        name: multipaper.jar
        path: build/libs/multipaper-paperclip-*-reobf.jar
    - continue-on-error: true
      name: Upload MultiPaper-Master jar
      uses: actions/upload-artifact@v2
      with:
        name: multipaper-master.jar
        path: MultiPaper-Master/build/libs/multipaper-master*.jar
name: Generate Jars
on:
  repository_dispatch:
    types: trigger-ga___build.yml
