jobs:
  upstream:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Git Repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2.5.0
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Configure Git User Details
      run: git config --global user.email "actions@github.com" && git config --global
        user.name "Github Actions"
    - continue-on-error: true
      name: Update Upstream Commit Hash
      run: ./gradlew purpurRefLatest --stacktrace
    - continue-on-error: true
      name: Apply Patches
      run: ./gradlew applyPatches --stacktrace
    - continue-on-error: true
      name: Build Paperclip jar
      run: ./gradlew jar createReobfPaperclipJar --stacktrace
    - continue-on-error: true
      name: Rebuild Patches
      run: ./gradlew rebuildPatches --stacktrace
    - continue-on-error: true
      name: Upload Paperclip jar
      uses: actions/upload-artifact@v2
      with:
        name: multipaper.jar
        path: build/libs/multipaper-paperclip-*-reobf.jar
    - continue-on-error: true
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        body: ''
        branch: update-upstream
        commit-message: Update Upstream
        delete-branch: true
        title: Update Upstream
name: Update Upstream
on:
  repository_dispatch:
    types: trigger-ga___upstream.yml
